services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
      POSTGRES_DB: quiz_app_web
    ports:
      - "5432:5432"
    volumes:
      - quiz_db_data:/var/lib/postgresql/data

volumes:
  quiz_db_data:
